package semantic

var ghSchema = Schema{
	Command:     "gh",
	order:       40,
	Description: "GitHub CLI api, pr, issue, repo, release, secret, search, workflow, auth, and run operations.",
	Parser:      "gh",
	Fields: []Field{
		stringField("area", "Top-level gh area such as api, pr, issue, repo, release, secret, search, workflow, auth, or run."),
		stringListField("area_in", "Allowed gh areas."),
		stringField("verb", "gh subcommand verb inside the selected area."),
		stringListField("verb_in", "Allowed gh verbs."),
		stringField("repo", "Repository selected by -R or --repo, or the target repository positional for gh repo commands."),
		stringListField("repo_in", "Allowed repositories."),
		stringField("org", "Organization selected by -o or --org."),
		stringListField("org_in", "Allowed organizations."),
		stringField("env", "Environment selected by -e/--env or --env-name."),
		stringListField("env_in", "Allowed environments."),
		stringField("hostname", "Hostname selected by --hostname."),
		stringListField("hostname_in", "Allowed hostnames."),
		boolField("web", "True when -w or --web is present."),
		stringField("method", "HTTP method for gh api."),
		stringListField("method_in", "Allowed gh api HTTP methods."),
		stringField("endpoint", "Normalized gh api endpoint."),
		stringField("endpoint_prefix", "Normalized gh api endpoint prefix."),
		stringListField("endpoint_contains", "Endpoint substrings that must be present."),
		boolField("paginate", "True when gh api --paginate is present."),
		boolField("input", "True when gh api --input is present."),
		boolField("silent", "True when gh api --silent is present."),
		boolField("include_headers", "True when gh api -i or --include is present."),
		stringListField("field_keys_contains", "gh api -F/--field keys that must be present."),
		stringListField("raw_field_keys_contains", "gh api -f/--raw-field keys that must be present."),
		stringListField("header_keys_contains", "gh api -H/--header keys that must be present."),
		stringField("pr_number", "Pull request number positional for gh pr commands."),
		stringField("issue_number", "Issue number positional for gh issue commands."),
		stringField("secret_name", "Secret name positional for gh secret commands."),
		stringListField("secret_name_in", "Allowed gh secret names."),
		stringField("tag", "Release tag positional for gh release commands."),
		stringField("workflow_name", "Workflow name positional for gh workflow commands."),
		stringField("workflow_id", "Workflow ID positional for gh workflow commands."),
		stringField("search_type", "Search type for gh search commands, such as code, commits, issues, prs, or repos."),
		stringListField("search_type_in", "Allowed gh search types."),
		stringField("query_contains", "Substring that must be present in the gh search query."),
		stringField("base", "Base branch selected by --base."),
		stringField("head", "Head branch selected by --head."),
		stringField("ref", "Ref selected by --ref."),
		stringListField("ref_in", "Allowed refs selected by --ref."),
		stringField("state", "Issue state selected by --state."),
		stringListField("state_in", "Allowed issue states."),
		stringListField("label_in", "Issue labels selected by -l or --label; at least one listed label must be present."),
		stringListField("assignee_in", "Issue assignees selected by -a or --assignee; at least one listed assignee must be present."),
		stringField("title_contains", "Substring that must be present in the issue title selected by -t or --title."),
		stringField("body_contains", "Substring that must be present in the issue body selected by -b or --body."),
		boolField("draft", "True when gh pr create --draft is present."),
		boolField("prerelease", "True when gh release create/edit --prerelease is present."),
		boolField("latest", "True when gh release create/view --latest is present."),
		boolField("fill", "True when gh pr create --fill is present."),
		boolField("force", "True for gh pr checkout --force or -f, and gh run rerun --force."),
		boolField("admin", "True when gh pr merge --admin is present."),
		boolField("auto", "True when gh pr merge --auto is present."),
		boolField("delete_branch", "True when gh pr merge --delete-branch is present."),
		stringField("merge_strategy", "Merge strategy selected by gh pr merge."),
		stringListField("merge_strategy_in", "Allowed merge strategies."),
		stringField("run_id", "Run ID positional for gh run commands."),
		boolField("failed", "True when gh run rerun --failed is present."),
		stringField("job", "Job selected by gh run rerun --job."),
		boolField("debug", "True when gh run rerun --debug is present."),
		boolField("exit_status", "True when gh run view --exit-status is present."),
		stringListField("flags_contains", "Parser-recognized gh option tokens that must be present; this does not scan raw argv words."),
		stringListField("flags_prefixes", "Parser-recognized gh option tokens that must start with these prefixes; this depends on the gh parser."),
	},
	Examples: []Example{
		{Title: "Deny mutating GitHub API calls", YAML: `permission:
  deny:
    - command:
        name: gh
        semantic:
          area: api
          method_in: [POST, PATCH, PUT, DELETE]`},
	},
}

func init() {
	RegisterSchema(ghSchema)
}
